const express = require("express")
const message = require("./routes/message")
const auth = require("./routes/auth")
const cors=require("cors")
const app = express()
app.use(express.json())
app.use("/auth", auth)
app.use("/message", message)
// app.use("/", mail)
// app.use("/", verify)
app.use(cors());
app.use((req, res, next)=>{
    res.setHeader("Access-Control-Allow-Origin", '*')
    res.setHeader("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE")
    res.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization")
    next()
})
app.listen(5000, () => {
    console.log("I started listening on http://localhost:5000")
})